permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Rado Dimitrov
url: https://zachholman.com/left
description: A fantastic blog that is fantastic.
twitter: radoslav_dimitr
linkedin: radoslavdimitrov
